# Uncomment this line to define a global platform for your project
 platform :ios, ‘8.0’

target 'iPhoneXMPP' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  
   use_frameworks!
   
   pod 'CocoaLumberjack/Swift'
    pod 'CocoaAsyncSocket'
    pod 'KissXML'

  # Pods for iPhoneXMPP

end
