# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'DemoUrdu' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~>2.0’
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Kingfisher', '~> 2.4'

  target 'DemoUrduTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoUrduUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
